name: Node CI
on:
  push:
    branches:
      - develop
      - gh-pages
  pull_request: {}

env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
  PUPPETEER_EXECUTABLE_PATH: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

jobs:
  lint:
    name: Check linting issues
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-12-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run lint

  test-headless:
    name: Headless Tests
    runs-on: macos-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-12-${{ hashFiles('**/package-lock.json') }}
      - name: install & build
        run: |
          npm ci
          npm run build:w3c
      - run: npm run test:headless

  test-karma:
    name: Karma Unit Tests (${{ matrix.browser }})
    strategy:
      matrix:
        os: ubuntu-latest
        browser: [ChromeHeadless, FirefoxHeadless]
        include:
          os: macos-latest
          browser: Safari
    runs-on: ${{ matrix.os }}
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-12-${{ hashFiles('**/package-lock.json') }}
      - name: install & build
        run: |
          npm ci
          npm run build:w3c & npm run build:geonovum
      - run: npm run test:karma
        env:
          BROWSERS: ${{ matrix.browser }}
